version: '3.9'

services:
  admin:
    container_name: adminartists
    image: nightcrawlers512/adminartists:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .docker.env
